### PR TITLE
Removed Zone_Li01_debris_practice_001

### PR DESCRIPTION
**Pull request by FireFlyEx**
Removed Zone_Li01_debris_practice_001

### CODE REVIEW

**Comment by erikroe** [comment]
Please rebase this commit on the current Main to not have a thousand IDS changes in it.

**Comment by erikroe** [comment]
Why did you remove this PR?

**Comment by FireFlyEx** [comment]
Because it's redundant and is resolved by the other one.

**Comment by erikroe** [comment]
Please do not mix different issues into one PR!

**Review by erikroe — APPROVED** [review]

**Pull request merged**
