### PR TITLE
Freelancer Space Suites Remaster

### PR DESCRIPTION
**Pull request by Worldwave**
Remaster of Freelancer's soundtrack in progress.

### CODE REVIEW

**Comment by erikroe** [comment]
@Worldwave
On `iw_battle` I think the loop sounds a bit odd. The kind of "rhythm" of those weird BRRR sequences does not match with the very last one in timing before it goes back to the beginning I would subjectively say after listening to it.

On `li_space` there is a little CLACK sound in the moment of the loop.

The `no_lair_battle` is missing.

The `rh_danger` has a kind of hearable difference between end and beginning with this background "brrr" noise. I thought in your previews it was less noticable. Maybe forgot a filter there or so?

On `rh_space` there is a little CLACK sound in the moment of the loop.

Other than this everything else is in really good shape.

**Comment by Worldwave** [comment]
Got it. Let's collect some more comments and I will apply.

**Review by FireFlyEx — APPROVED** [review]
Excellent. Would eat here again. 5/5

**Comment by Worldwave** [comment]
iw_battle complete
li_space complete
rh_danger complete
rh_space complete
no_lair_battle added

**Comment by erikroe** [comment]
@Worldwave There is still a clack at the end of the RH Space Music.
At the beginning of Li Space there's an instant click, and just like a second after too, when hearing it looped. But it's very tiny and won't be hearable at all in the game.
I will be merging this now anyway for the upcoming patches. The files I am going to convert to MP3s with 320kbit to compress them down without sacrificing the sound quality.

**Pull request merged**
