### PR TITLE
Reduced Zone 21 size

### PR DESCRIPTION
**Pull request by FireFlyEx**
Reduced Zone 21 size, including exclusion.
Moved buoys to mark the new exclusion position.
Removed temporary patrol route that was inside the exclusion previously.

### CODE REVIEW

**Comment by erikroe** [comment]
Please rebase this branch on the current Main to not have a thousand IDS changes in it.

**Comment by FireFlyEx** [comment]
Rebased

**Review by erikroe — CHANGES_REQUESTED** [review]
There is still a hundred changed IDS

**Comment by FireFlyEx** [comment]
No there aren't. I pulled straight from github and updated that file with the changes.

**Comment by erikroe** [comment]
Seems like Github didn't update it correctly. Now it looks fine. Sorry!

**Review by erikroe — APPROVED** [review]

**Pull request merged**
