### PR TITLE
Fixed Buffalo base interior

### PR DESCRIPTION
**Pull request by FireFlyEx**
**Li01_12_Bar.ini**
 - Changed **[CharacterPlacement]:start_script** to **Scripts\Bases\li_09_Bar_enter_01.thn** to eliminate the following spew:
```
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3020) : WARNING:General:set_material() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3687) : WARNING:General:set_texture_stage_texture() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3586) : WARNING:General:set_render_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3717) : WARNING:General:verify_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3667) : WARNING:General:set_texture_stage_transform() called outside of create_buffers/destroy_buffers
```

**Li01_12_Deck.ini & Li01_12_Deck2.ini**
 - Changed **[Room_Info]:scene** to **all, ambient, Scripts\Bases\li_06_Deck_ambi_int_01.thn** to keep interior consistent
 - Changed **[Room_Info:set_script** to **Scripts\Bases\li_06_Deck_hardpoint_01.thn** to keep interior consistent
 - Removed hardpoint references to _HpLightA29-A40_ and one [FlashlightSet] block to match with the new scene script

### CODE REVIEW

**Review by erikroe — CHANGES_REQUESTED** [review]
Looks good, but there's one error in my log:
`E:\FL\Scratch\Source\Client\GF\ScriptLight.cpp(375) : *** WARNING: invalid light reference to name Ambi_Lightning_ALL_LtG23_Trgt`
I think it comes from Buffalo.

**Comment by FireFlyEx** [comment]
`I checked the li_09_bar_ambi_li01_12.thn file and it looks like you actually added the broken light: Ambi_Lightning_ALL_LtG23_Trgt. Why did you do that?

The last fix here is to revert that thn file back to vanilla. Unless you have a good explanation why you added that light.`
That can be ignored since it is a different issue.

**Comment by erikroe** [comment]
> That error is caused by a modified **li_09_bar_ambi_li01_12.thn** file that **Ambi_Lightning_ALL_LtG23_Trgt** was added to and shouldn't have been. It's in HDE and shouldn't be. There is nothing for us to fix.

That cannot be because this THN is not delivered by FLSR and so on my PC at least I have a default one of the vanilla game.

**Comment by FireFlyEx** [comment]
I have confirmed that **Ambi_Lightning_ALL_LtG23_Trgt** was in the original **li_09_bar_ambi_li01_12.thn** file (2/4/2003) from the game _straight off the CD_. It was first deleted by Adoxa in JFLP on 5/19/2009 and has propagated forward from there.

**Comment by erikroe** [comment]
Do you have the working one on your PC and can upload it?

**Comment by FireFlyEx** [comment]
Already did.

**Review by erikroe — APPROVED** [review]

**Pull request merged**
